site_name: Unattended Server
site_description: 'Project documentation'
site_author: 'Donovan Solms'
site_url: 'https://docs.projectlimitless.io/unattended-server'
project_url: '/unattended-server'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/ProjectLimitless/UnattendedServer'

# Copyright
copyright: 'Copyright &copy; Donovan Solms'

theme_dir: '_theme/material'
docs_dir: './unattended-server/docs'
extra:
  logo: images/limitless-logo.png
  author:
    github: 'ProjectLimitless'
    twitter: 'prjlimitless'

markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

# Page tree
pages:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Publishing Updates: publishing-updates.md
