site_name: Badger
site_description: 'Project documentation'
site_author: 'Donovan Solms'
site_url: 'https://docs.projectlimitless.io/badger'
project_url: '/badger'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/ProjectLimitless/Badger'

# Copyright
copyright: 'Copyright &copy; Donovan Solms'
google_analytics: ['UA-26768009-4', 'docs.projectlimitless.io']

theme_dir: '_theme/material'
docs_dir: './badger/docs'
#theme: 'material'
extra:
  logo: images/limitless-logo.png
  author:
    github: 'ProjectLimitless'
    twitter: 'prjlimitless'

markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

# Page tree
pages:
  - Overview: index.md
  - Getting Started: getting-started.md
  - Project File Format: project-file-format.md
  - Project Pages: project-pages.md
