site_name: Badger
site_description: 'Project documentation'
site_author: 'Donovan Solms'
site_url: 'https://docs.projectlimitless.io/Badger'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/ProjectLimitless/Badger'

# Copyright
copyright: 'Copyright &copy; Donovan Solms'


theme: 'material'
extra:
  palette:
    primary: 'blue grey'
    accent: 'blue'
  author:
    github: 'ProjectLimitless'
    twitter: 'prjlimitless'
